### PR TITLE
Add support for settings custom headers to backend bucket

### PR DESCRIPTION
**Pull request by MeNsaaH**

### CODE REVIEW

**Comment by MeNsaaH** [comment]
@robmorgan is there any hope for merging this PR?

**Comment by othree** [comment]
Any update on this PR. There is no response from any maintainer?

**Comment by Etiene** [comment]
Apologies for the delay in responding to this PR. Please see below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io.

**Comment by TheNotary** [comment]
> A web application uses HTTPS and a URL-based session identifier. The web application might wish to link to HTTPS resources on other web sites without leaking the user’s session identifier in the URL.  - From [w3.org](https://www.w3.org/TR/referrer-policy/#:~:text=3.4.-,%22%20origin%20%22,like%20https%3A%2F%2Fexample.com%20.) 

This looks like it would be very important for hosting some applications that contain sensitive data in the url.  The PR looks clean to me (a passer by who also likes this repo), but maybe the default configurations should set a lesser intrusive `same-origin` value because it may cause confusion if engineers are expecting referrer information in their own code and overlook this setting?

**Comment by MoonMoon1919** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-static-assets#sunset-notice)

**Pull request closed without merging**
