### PR TITLE
Update repo to work with Terraform 0.13.x

### PR DESCRIPTION
**Pull request by robmorgan**
1. Update CircleCI to use Terraform 0.13.x.
1. Update the version constraint on all examples to require at least Terraform 0.12.26.
1. Update pre-commit hooks to add `gofmt`.
1. Drop Go Dep in favor of Go modules.
1. Upgrade the tests to support Terratest v0.30.23

In general, TF 0.13.x seems backwards compatible from a testing perspective: I did not need to change anything in `modules` in this PR. I've also ensured the modules and examples work with Google Provider 3.x.

### CODE REVIEW

**Comment by robmorgan** [comment]
Waiting for an admin to re-enable the CircleCI tests.

**Comment by robmorgan** [comment]
Ok that's done, this PR is now ready for review!

**Review by rhoboat — APPROVED** [review]
LGTM. I checked the CI yaml and everything else looks good, too.

**Comment by robmorgan** [comment]
thanks @rhoboat !

**Pull request merged**
